### ISSUE TITLE
[BUG] Unable to create/modify multi-line keyPair values with PowerCommander

### ISSUE THREAD

**Issue by sethwalker1** [Keeper-Security/keeper-sdk-dotnet#109]
I'm trying to create an SSH Key record that holds a GPG key using PowerCommander.

```powershell
$outputRecord = Add-KeeperRecord -RecordType sshKeys -Title $title -login $email -host $hostname -notes $notes "keyPair=$publicKey"
```

This code populates the `Private Key` field with the first line of the GPG key, but no more because multi-line inputs are not supported. I've tried saving without spacing, but the key is considered invalid if I do so.

Possible solutions:
1. Adding `keyPair` argument to the `Add-KeeperRecord` cmdlet
2. Some way of escaping new lines?
3. Modifying [this regex](https://github.com/Keeper-Security/keeper-sdk-dotnet/blob/d3f56bbb0a7e89231a0329c162293e15ca48ffa6/PowerCommander/RecordCommands.ps1#L324) to allow using quotation marks for multi-line inputs

**Comment by sk-keeper** [comment]
`keyPair` is a complex field. You can see field format by running `Get-KeeperRecordType -ShowFields`
```
privateKey       privateKey       Optional {'publicKey': '', 'privateKey': ''}
```
Fields like `keyPair` expect hash tables as field value
```
$publicKey = @{'publicKey'='PUBLICKEY'; 'privateKey'='PRIVATE KEY'}
Add-KeeperRecord -RecordType sshKeys -Title $title -login $email -host $hostname -notes $notes -keyPair $publicKey
```
