### ISSUE TITLE
GetUsersForShare() Method Returning Empty Lists

### ISSUE THREAD

**Issue by YoussefFenetre** [Keeper-Security/keeper-sdk-dotnet#133]
Description:
I am encountering an issue where the GetUsersForShare() method from the Keeper SDK consistently returns empty lists for SharesWithUsers, SharesFromUsers, and GroupUsers. Based on the documentation and expected behavior, these properties should contain user information relevant to sharing contexts, but they are all empty despite having users in the system.

**Steps to Reproduce:**

1. Authenticate and initialize the Keeper vault using the SDK.
2. Call the GetUsersForShare() method.
3. Observe that the response contains empty lists for SharesWithUsers, SharesFromUsers, and GroupUsers.

**Expected Behavior:**

The GetUsersForShare() method should return populated lists for one or more of the following, depending on the sharing context:

- SharesWithUsers: Users I have shared records or folders with.
- SharesFromUsers: Users who have shared records or folders with me.
- GroupUsers: Users in my enterprise or team groups.

**Observed Behavior:**

The method executes successfully, but the returned lists are empty:

- SharesWithUsers: []
- SharesFromUsers: []
- GroupUsers: []

Questions/Concerns:

1. Are there any specific conditions (e.g., permissions, sharing history, account type) that could result in empty lists being returned?
2. Is there additional configuration required to ensure this method works as expected?

Thank you in advance!

**Comment by sk-keeper** [comment]
This method uses obsolete backend API. Though that API returns valid information for my account.

Keeper SDK v 1.0.7 Beta 01 uses the latest backend API to retrieve usernames for sharing.

**Comment by YoussefFenetre** [comment]
Thank you Keeper SDK v 1.0.7 Beta 01 does solve my issue
