### ISSUE TITLE
PowerCommander - Custom Fields

### ISSUE THREAD

**Issue by mxiong-PTI** [Keeper-Security/keeper-sdk-dotnet#18]
Not really an issue here but I couldn't figure out a way to add multiple custom fields when creating a new record and I was wondering if there is a way to do that when using the Add-KeeperRecord. 

For example:

Add-KeeperRecord -Title 'Test Record' -Login 'Test User' -password 'Test Password' -URL 'WWW.Test.com' -Custom 'Name1:TestCust1'  'Name2:TestCust2' 

Thanks,

Ma Xiong

**Comment by mxiong-PTI** [comment]
I've tried the above and instead of creating new custom fields, It adds them all into the first one.

Here is the code I tried.
Add-KeeperRecord -Title 'Test Record' `
                 -Login 'TESTUSERNAME' `
                 -Password 'TESTPASSWORD' `
                 -URL 'WWW.URL.COM' `
                 -Custom "Cust1:TestCust1, Cust2:TestCust2, cust3:TestCust3"

Below is the screenshot of the record created in Keeper
![image](https://user-images.githubusercontent.com/63819395/91050354-26886a80-e5e4-11ea-9875-91a90b7b3485.png)

**Comment by sk-keeper** [comment]
`Add-KeeperRecord "Record Title" -UpdateOnly -Custom a:b, c:d` works fine
-Custom parameter accepts array of strings.
-Custom "Cust1:TestCust1, Cust2:TestCust2, cust3:TestCust3"   - incorrect
-Custom "Cust1:TestCust1", "Cust2:TestCust2", "cust3:TestCust3"  - correct

**Comment by mxiong-PTI** [comment]
Thank you for clarifying that up!
