### ISSUE TITLE
ConsoleAutUI.cs

### ISSUE THREAD

**Issue by mjohl** [Keeper-Security/keeper-sdk-dotnet#22]
The code does not work and goes into an infinite loop for the WaitForUserPassword method.
The older AuthUI.cs that wrapped that return in a task worked fine.

**Comment by sk-keeper** [comment]
Do you use ConsoleAuthUI.cs in your application?
Does Commander sample app do the same?

**Comment by mjohl** [comment]
I believe the problem to be the await InvokePasswordActionDelegate(password)., What is that supposed to do inorder for the while loop to exit?

**Comment by sk-keeper** [comment]
Either empty or valid password exits that loop.

Empty password cancels login session
if (string.IsNullOrEmpty(password)) return false;

Valid password breaks the loop.
                try
                {
                    await info.InvokePasswordActionDelegate(password);
                    break;
                }
...
return true;

**Comment by sk-keeper** [comment]
no response from the customer

**Comment by jodel9227** [comment]
Hello, I'm also encountering an infinite loop issue with the WaitForUserPassword method in a Winforms app. Whenever I enter a wrong/empty password, everything works as expected, but when I enter the correct one, it just prompts me again.

try
{
    await passwordInfo.InvokePasswordActionDelegate(password);
}
catch(Exception e)
{
    return false;
}

return true;
