### ISSUE TITLE
Add Module to PowerShell Gallery

### ISSUE THREAD

**Issue by PDQDakota** [Keeper-Security/keeper-sdk-dotnet#32]
Is there anything that's preventing PowerCommander from being added to the PowerShell Gallery?

The use case would be to enable installation via Install-Module rather than copying the module in to `%USERPROFILE%\Documents\WindowsPowerShell\Modules` or `C:\Program Files\WindowsPowerShell\Modules` manually. More or less like how Nuget functions for the SDK itself.

**Comment by sk-keeper** [comment]
Thank you for feedback.
Nothing prevents PowerCommander from being published to the PowerShell Gallery.
We just haven't had a request yet.
The request ticket is created.

**Comment by PDQDakota** [comment]
Thank you for the quick reply! It would really help out to ease distribution/installation of this module if you all are able to get it published on to the gallery the regular.

**Comment by Surowa** [comment]
I agree. A PowerCommander PS module would be helpful for us as well.

**Comment by sk-keeper** [comment]
PowerCommander module was added as an example of using .Net SDK with PowerShell.
It's never been targeted as a mature "product" that is ready to be published to the PowerShell Gallery.

**Comment by thx1200** [comment]
Even if this is a beta product, I think it would benefit all users to publish it to the Gallery.

**Comment by PiotrBaran1010** [comment]
@sk-keeper is this still the case? Looks like this module does see some development from time to time? Maybe you will reconsider adding it to the gallery now?

**Comment by sk-keeper** [comment]
PowerCommander is finally published to PowerShell Gallery.
A few cmdlets have been renamed to comply with cmdlet naming convention.
