### ISSUE TITLE
Exception when running Import-Module PowerCommander

### ISSUE THREAD

**Issue by rduncanpph** [Keeper-Security/keeper-sdk-dotnet#33]
I've copied the directory listed in the setup instructions. Ran the Connect-Keeper command and received the following exception...

Connect-Keeper : The 'Connect-Keeper' command was found in the module 'PowerCommander', but the module could not be loaded. For more information, run 'Import-Module PowerCommander'.
At line:1 char:1
+ Connect-Keeper
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-Keeper:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

When running Import-Module PowerCommander I receive the following exception...

Import-Module : Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\PowerCommander\KeeperSdk.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module PowerCommander
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Please advise. Thank you!

**Comment by sk-keeper** [comment]
It looks like the dlls are not loaded by the system. Error: 0x80131515
Please check this stackoverflow article
https://stackoverflow.com/questions/34400546/could-not-load-file-or-assembly-operation-is-not-supported-exception-from-hres

Basically, dlls are marked as downloaded from the internet and system rejects loading them

**Comment by rduncanpph** [comment]
Looks like my machine just needed a reboot. All set. Thank you!
