### ISSUE TITLE
Error with the 'Move-RecordToFolder' command

### ISSUE THREAD

**Issue by eaksel** [Keeper-Security/keeper-sdk-dotnet#59]
Hello,

I've tried using the 'Move-RecordToFolder' command, however I'm getting the following error:

> Exception calling "GetResult" with "0" argument(s): "An error has occurred.  Please check if an update is available for your device on the App Store or the Keeper Security website.  If you continue to
> receive this error, please email support@keepersecurity.com or contact us at https://keepersecurity.com/support.html and let us know that error code (move) has occurred."
> At D:\Users\<username>\Documents\WindowsPowerShell\Modules\PowerCommander\RecordCommands.ps1:503 char:3
>     +         $vault.MoveRecords($sourceRecords, $folderUid, $Link.IsPresen ...
>     +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : KeeperApiException

I've tried the  'Move-RecordToFolder' command with the following parameters:
`Move-RecordToFolder -Folder "<folder_uid>" -Records @("<record_uid>")`
`Move-RecordToFolder -Folder "<folder_uid>" -Records "<record_uid>"`

I've tried versions 1.0.3, 1.0.4-beta4 and 1.0.4-beta6.

Am I using the command the wrong way, or is there an issue with it ?

Thanks

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. This command was not record types aware and accepted owned records only.
Both issues has been fixed. You can use either UID or Path for -Folder and -Records parameters. 
Please get the latest changes from the repository.

Thanks

**Comment by eaksel** [comment]
I can confirm that I can move records to folders using the path, however when using the UID I get the following error:

resolveFolderNode : Folder B7hCvIBSasm5OCEs6w_XYZ not found
At D:\Users\<username>\Documents\WindowsPowerShell\Modules\PowerCommander\RecordCommands.ps1:443 char:17
    +         $folderNode = resolveFolderNode $vault $Folder
    +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,resolveFolderNode


Also just FYI, I've tried moving a records into a shared folder and they are showing using the "Get-KeeperChildItems" and the Web vault, but not on the dektop app (version 16.6.1 x64), I've tried restarting it but to no avail. The issue isn't happening when moving them to a non-shared folder.

I've used this command to create the records that are buggy on the desktop app:
Add-KeeperRecord -RecordType 'Login' -Title "Test PowerShell" -Fields @("login=username"; "password=password")

Thanks,

**Comment by sk-keeper** [comment]
Folder UID issue is fixed. 
Also, `Add-KeeperRecord` cmdlet now supports -Folder parameter. There is no need for subsequent `Move-RecordToFolder`.
-Folder parameter supports folder name auto completion

The desktop app should support auto vault refresh when data is changed. Probably, the Websocket connection that is used to receive push notifications from the backend was dropped. 

Thanks,

**Comment by eaksel** [comment]
Hi,

I can confirm that everything works as expected now, and the feature to specify the folder when creating a record is great.

Thanks a lot !
