### ISSUE TITLE
Connect-Keeper does not support secure string password 

### ISSUE THREAD

**Issue by Project2022Energy** [Keeper-Security/keeper-sdk-dotnet#61]
The following code does not work 

$tmp = Read-Host "Enter Password" -AsSecureString 

Connect-Keeper -Username "use@domain.com" -Password $tmp

I wonder whether the PS module supports "System.Security.SecureString"

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. It will be fixed in the next release.

**Comment by jossemann88** [comment]
Any ETA on this? Would also like to see this implemented.

**Comment by sk-keeper** [comment]
The fix is pushed to master.
https://github.com/Keeper-Security/keeper-sdk-dotnet/commit/e4acfb9443044f2524eca3342e2cd516808660f6
Thanks
