### ISSUE TITLE
Cannot receive TOTP code

### ISSUE THREAD

**Issue by mtevs** [Keeper-Security/keeper-sdk-dotnet#62]
I wrote a script and part of what it does is get a TOTP code. If I run the script locally I get the TOTP codes. I try running the same exact script on a Virtual Machine and I am not able to get TOTP codes. If I try to do "UID | 2fa" I get nothing.

**Comment by sk-keeper** [comment]
"kr | 2fa"   returns TOTP codes for all records in the vault.
Do you have the same results on your computers when logged to the same account?

**Comment by mtevs** [comment]
If I run this command locally on my computer it works just fine. If I try to run it on a virtual machine it gives me an error.
