### ISSUE TITLE
Bug? Using Power Commander login (Connect-Keeper) and Secret Manager Powershell Plugin

### ISSUE THREAD

**Issue by cr2023** [Keeper-Security/keeper-sdk-dotnet#68]
Replication

- Powershell: Version 7.2
- Install Power Commander in the Windows Powershell Module
- Install Secrets Manager Powershell 

Store the username and password in keeper.
If you have the line codes to pull the username and password from secrets manager, if you do the "connect-keeper" script to login into powercommander after using the secrets manager code (different framework), it errors out. But if you do it before the code, it works. Which means you can't utilize secrets manager to pull the login information for powercommander to login with.

In sense it seems to be a compatibility issue with using secrets manager with the connect-keeper function. Connect-keeper works before using any secrets manager function but not after.

New-Object: C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:359
Line |
 359 |  … $endpoint = New-Object KeeperSecurity.Authentication.KeeperEndpoint($ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "2" argument(s): "Could not load file or assembly 'BouncyCastle.Crypto,
     | Version=1.9.0.0, Culture=neutral, PublicKeyToken=*******'. Could not find or load a specific
     | file. (0x80131621)"

InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:360
Line |
 360 |      $endpoint.DeviceName = 'PowerShell Commander'
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'DeviceName' cannot be found on this object. Verify that the property exists and can be
     | set.

InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:361
Line |
 361 |      $endpoint.ClientVersion = 'c16.1.0'
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'ClientVersion' cannot be found on this object. Verify that the property exists and can
     | be set.

New-Object: C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:362
Line |
 362 |  … $authFlow = New-Object KeeperSecurity.Authentication.Sync.AuthSync($s …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "2" argument(s): "Could not load file or assembly 'BouncyCastle.Crypto,
     | Version=1.9.0.0, Culture=neutral, PublicKeyToken=******. Could not find or load a specific
     | file. (0x80131621)"

InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:364
Line |
 364 |      $authFlow.ResumeSession = $true
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'ResumeSession' cannot be found on this object. Verify that the property exists and can
     | be set.

InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:365
Line |
 365 |      $authFlow.AlternatePassword = $SsoPassword.IsPresent
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'AlternatePassword' cannot be found on this object. Verify that the property exists and
     | can be set.

    Keeper Username:  *****
InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:397
Line |
 397 |          $authFlow.Login($Username, $passwords).GetAwaiter().GetResult …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:52
Line |
  52 |      $prompt = "`nUnsupported ($($auth.step.State.ToString()))"
     |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

**Comment by cr2023** [comment]
So in sense can't seem to use "Connect-keeper" command **after** using get-secret command but you can if you use it **before**.

**Comment by sk-keeper** [comment]
PowerCommander targets .Net Framework
Secrets-Manager targets .Net Core
Both use BouncyCastle encryption library.

PowerCommander cannot load .Net BouncyCastle library if .Net Core version of this library is already loaded.

We'll probably need to provide .Net Core version of PowerCommander that works with Secrets Manager for Powershell

**Comment by sk-keeper** [comment]
PowerCommander and SecretManager scripts reference different versions of `BouncyCastle.Crypto.dll` library: 1.9.0 and 1.8.10 accordingly.
This version conflict can be resolved by replacing `BouncyCastle.Crypto.dll` in PowerCommander with the same file from the SecretsManager.

PowerShell 7.0 installs SecretsManager module in %HOME%\Documents\PowerShell\Modules\SecretManagement.Keeper\... folder

**Comment by cr2023** [comment]
Perfect, that was exactly it and resolved it. Thank you.

**Comment by sk-keeper** [comment]
SecretsManager Powershell module has been upgraded to match shared library dependencies.
When updated to Keeper SecretsManager 16.3.3 please revert `BouncyCastle.Crypto.dll` file in PowerCommander module
otherwise SecretsManager will stop working after launching PowerCommander.

I seems that there is no easy solution to this issue other than making sure shared libraries use the same version.
