### ISSUE TITLE
Read-Host not working in non-interactive shells when running Powershell cmdlets

### ISSUE THREAD

**Issue by Surowa** [Keeper-Security/keeper-sdk-dotnet#73]
Please change Read-Host to something that can be used interactively, e.g. via Puppet or Ansible. 
I'm not sure what triggers this exactly but I presume it's either Connect-Keeper, Sync-Keeper, get-keeperrecords, or Copy-KeeperToClipboard(as I don't use any other cmdlets in the piece of code I'm trying.)

```
 Read-Host : The method or operation is not implemented.
At C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:409 char:32
$securedPassword = Read-Host -Prompt $prompt -AsSecureString
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Read-Host], NotImplementedException
+ FullyQualifiedErrorId : System.NotImplementedException,Microsoft.PowerShell.Commands.ReadHostCommand
```

**Comment by sk-keeper** [comment]
This line is invoked by `Connect-Keeper` command when password is required to resume authentication with Keeper.
Some Powershell environments (Azure functions as an example) do not provide user interaction and `Read-Host` fails.

There are two solutions:

1. `Connect-Keeper` cmdlet accepts -Password parameter 

2. Keeper device(instance or installation) can be configured for passwordless login (or stay logged in)
Please see this document starting Item #12
https://docs.keeper.io/sso-connect-cloud/device-approvals/azure-function
The configuration file `config.json` needs to be created and configured with .Net Commander.exe application.
Once this file is uploaded to non-interactive Powershell environment `Connect-Keeper` starts using it.
Please let us know if there are better way to overcome this `Read-Host` issue.

Thank you

**Comment by Surowa** [comment]
Okay clear, I think it just didn't properly inject the -Password parameter as it works now. Thanks!
