### ISSUE TITLE
The property 'AvailableTeams' cannot be found on this object.

### ISSUE THREAD

**Issue by thx1200** [Keeper-Security/keeper-sdk-dotnet#86]
I copied the PowerCommander folder to Modules folder for all users.  When I try to sign in, I get the below error.  

```
The property 'AvailableTeams' cannot be found on this object. Verify that the property exists and can be
set.
At C:\Program Files\WindowsPowerShell\Modules\PowerCommander\AuthCommands.ps1:483 char:5
+     $Script:Context.AvailableTeams = $null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
```

**Comment by thx1200** [comment]
That is exactly what I am doing.  Windows 10.  PowerShell 5.1.19041.2364

**Comment by thx1200** [comment]
Any update?  This module isn't working for me at all even on fresh installation.

**Comment by sk-keeper** [comment]
It looks like PowerCommander folder is not loaded as a module. Module initialization code was not called.
To list installed modules:
https://learn.microsoft.com/en-us/powershell/module/powershellget/get-installedmodule?view=powershell-5.1
To import module 
https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/Import-Module?view=powershell-5.1

**Comment by Surowa** [comment]
Now that the module is published in the PSGallery installation should be much simpler.
A simple `Install-Module PowerCommander` (or `Install-Module PowerCommander -AllowClobber`) should suffice.
