### ISSUE TITLE
Get-KeeperMspLicenses command does not exist

### ISSUE THREAD

**Issue by Trefex** [Keeper-Security/keeper-sdk-dotnet#89]
It seems the `Get-KeeperMspLicenses` command does not exist in the PowerCommander cmdlet list.

Thanks,
T

**Comment by sk-keeper** [comment]
Yes, that is correct. 
PowerCommander  supports these MSP cmdlets
* Get-KeeperManagedCompanies
* New-KeeperManagedCompany
* Remove-KeeperManagedCompany
* Edit-KeeperManagedCompany

What information you would expect `Get-KeeperMspLicenses` cmdlet to return in terms of Python's Commander?
`msp-billing-report` ?

**Comment by Trefex** [comment]
@sk-keeper good question, as it is listed in the docs, I thought it would exist, I am not sure what it could return though.

In general though, it would be nice to be able to get licensing information for my specific tenant / company via CLI.

**Comment by quog** [comment]
@sk-keeper Can I second adding Get-KeeperMSPLicenses?  I would like to script fetching our MSP billing for the month in Powershell and the windows commander.exe appears to be only interactive (and I'm not a Python guy.)

**Comment by sk-keeper** [comment]
We can add a command similar to Commander's msp-billing-report

**Comment by sk-keeper** [comment]
`Get-MspBillingReport` command is added to Powershell module
