### ISSUE TITLE
Auto-login does not take --resume and --alt into account

### ISSUE THREAD

**Issue by LennardF1989** [Keeper-Security/keeper-sdk-dotnet#92]
Hello,

I want to use the SDK to automate some administrative tasks. One thing I'm playing with is to allow users to request access to shared folders through an internal web portal. My support team should then be able audit the request and provide access with the press of a button.

Obviously, security for Keeper is tight and you need to jump through some hoops to talk to the API. In order to do the above, I need some sort of persistent login, otherwise my support team will constantly have to re-login the web application, and that kind of defeats the point of the whole idea.

So, in order to achieve persistent login:
- I need an account with a Master Password, assuming (and please correct):
   - SSO login does not work, since you have to go through the challenge every time?
   - No 2FA enabled, or 2FA enabled but with duration set to forever*?
      - \* Or rather hacky, but the web app itself can generate the 2FA code when required. 
      - But what would the recommended approach be for this? I'm contemplating setting up the Vault once, then lock down all access except Commander, but I still don't want to make it too easy for anyone with the credentials to gain access, obviously...
- I do the login using the Commander once to setup the config.json
- After that, I keep my session alive by connecting to Keeper every 12 hours.
   - This is based on https://github.com/Keeper-Security/keeper-sdk-examples/tree/main/AzureAdminAutoApprove - but where can I set the timeout delay, is that an account setting?

Thanks!

**Comment by LennardF1989** [comment]
> Please use the latest .Net Commander build. https://github.com/Keeper-Security/keeper-sdk-dotnet/releases/tag/v1.0.5-beta07 It has persistent login bug fixed.

I'm running of master, did the commands, this-device shows things as I want them, but every time I restart the Commander, it will ask for a SSO token. 

How can I check if my enterprise has persistent login disabled? When I go into the vault I can freely check/uncheck "Remain logged in", the only thing that's required is the logout timer (which has a maximum of 480 minutes, so 8 hours),

**Comment by LennardF1989** [comment]
Okay, apparently `_auth.ResumeSession` has to be set to true in Commander through `LoginOptions`, then it works.

So, just to be sure, ResumeSession = true, if used within the Timeout window, will keep the account logged in indefinitely?

**Comment by LennardF1989** [comment]
@sk-keeper A workaround to start properly is to set last_login to "username@tld.com --resume --alt" for example, but it only works once, because after the next login the config.json is updated again.

I would like to propose to also persist ResumeSession and AlternatePassword in the config.json, so that information can be used when the `login` command is queued in `NotConnectedCommands`

**Comment by sk-keeper** [comment]
> So, just to be sure, ResumeSession = true, if used within the Timeout window, will keep the account logged in indefinitely?
Yes, that is correct

**Comment by sk-keeper** [comment]
Sorry. The latest changes in `release_1.0.5_beta07` branch was not been pushed to master branch.
https://github.com/Keeper-Security/keeper-sdk-dotnet/commit/a6003b81ad6db2d370a8e0ffa3f4f42b30674053

Thank you for pointing it out.
