### ISSUE TITLE
Copy-KeeperToClipboard fails to return Password

### ISSUE THREAD

**Issue by joergrenn** [Keeper-Security/keeper-sdk-dotnet#95]
I am using Copy-KeeperToClipboard cmdlet to retrieve a password from a record.
However I am always getting the message: "Record XXX has no Password"
I have tried several records that all have a password set. 
With "ko" it returns a password.

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. It's been fixed in the master branch
