### ISSUE TITLE
Record sharing error Grant-KeeperRecordAccess

### ISSUE THREAD

**Issue by Surowa** [Keeper-Security/keeper-sdk-dotnet#99]
Hi Keeper team.
I'm trying the following code snippet:

```
$client_number = client0001
$user = someuser@somecompany.com

$records = Get-KeeperRecord | Where-Object Title -like $client_number
        foreach($record in $records){
            $Uid = $record.Uid
            $RecordType = Get-KeeperObject -Uid $Uid -PropertyName Login
             if($RecordType -eq 'Slot 5 password'){
                 Grant-KeeperRecordAccess -Record $record -User $user
             }
         }
```

Gives the following exception:

```
Exception calling "GetResult" with "0" argument(s): "length=16, value=PersonalScopeUid"
At C:\Program Files\WindowsPowerShell\Modules\PowerCommander\0.9.1\Sharing.ps1:106 char:17
+ ...             $vault.ShareRecordWithUser($rec.Uid, $User, $CanShare.IsP ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : KeeperApiException
```

if I add -CanShare:$true, that gives the same error.

Bug or am I doing something wrong?
The error is not very informative in any case. 

I am using the latest PowerCommander version published to the PSGallery.

**Comment by sk-keeper** [comment]
It is hard to tell where this bug originates at at the moment.
"KeeperApiException" and "length=16, value=PersonalScopeUid" in error means this error is returned by the backend.
Most likely `$rec.Uid` has value `PersonalScopeUid`. The backend expects RecordUid to have length 22 or 23  (16 bytes url encoded) and rejects request.

It looks like you are trying share a non existing at the backend record.
Can you check `$record` that you are trying to share?

**Comment by Surowa** [comment]
The record most definitely exists, retrieving it with Get-KeeperRecord and Get-KeeperObject works fine. The account used to login has the rights to edit, share and read the record. 

Even hardcoding in the username and Uid does not work: Grant-KeeperRecordAccess -Record "jQUsnMytF49jYEHe_X1TyA" -User "user@company.com" -CanShare

Still gives the same error. Any way to increase the debug logging? Not too familiar with underlying .NET SDK troubleshooting..

**Comment by sk-keeper** [comment]
This issue has been duplicated. The fix is coming shortly

**Comment by sk-keeper** [comment]
PowerCommander 0.9.4 shoud have this issue fixed. Thank you for reporting it.
